apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ubuntu-ds
  labels:
    addonmanager.kubernetes.io/mode: ubuntu
spec:
  template:
    metadata:
      labels:
        app: ubuntu-ds
    spec:
      containers:
      - name: jial-ubuntu
        image: ubuntu:16.04
        command: ["/bin/bash","-c",  "sleep infinity"]
